[package]
name = "pass_vault"
version = "0.1.0"
authors = ["Nasir Hemed <nhemed@analytics.deloitte.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.1"
"serde" = "1.0.102"
self_encryption = "0.15.0"